# Allow access via IP address and standard browser headers
SecRuleRemoveById 920350
SecRuleRemoveById 920450

SecRule REQUEST_URI "@beginsWith /admin/backup/upload" \
    "id:1000,\
    phase:1,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"

SecRule REQUEST_URI "@beginsWith /admin/backup/upload" \
    "id:1001,\
    phase:2,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"

SecRule REQUEST_URI "@beginsWith /admin/log-viewer" \
    "id:1002,\
    phase:1,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"

SecRule REQUEST_URI "@beginsWith /admin/log-viewer" \
    "id:1003,\
    phase:2,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"

SecRule REQUEST_URI "@beginsWith /admin/log-viewer" \
    "id:1004,\
    phase:3,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"

SecRule REQUEST_URI "@beginsWith /admin/log-viewer" \
    "id:1005,\
    phase:4,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"

# Livewire & Scanner Page exclusions
SecRule REQUEST_URI "@beginsWith /livewire"     "id:1010,    phase:1,    pass,    nolog,    ctl:ruleRemoveById=941160,    ctl:ruleRemoveById=941100,    ctl:ruleRemoveById=941110,    ctl:ruleRemoveById=941120,    ctl:ruleRemoveById=941130,    ctl:ruleRemoveById=941140,    ctl:ruleRemoveById=941150,    ctl:ruleRemoveById=941170,    ctl:ruleRemoveById=941180,    ctl:ruleRemoveById=941320,    ctl:ruleRemoveById=941330,    ctl:ruleRemoveById=941340"

SecRule REQUEST_URI "@beginsWith /livewire"     "id:1011,    phase:2,    pass,    nolog,    ctl:ruleRemoveById=941160,    ctl:ruleRemoveById=941100,    ctl:ruleRemoveById=941110,    ctl:ruleRemoveById=941120,    ctl:ruleRemoveById=941130,    ctl:ruleRemoveById=941140,    ctl:ruleRemoveById=941150,    ctl:ruleRemoveById=941170,    ctl:ruleRemoveById=941180,    ctl:ruleRemoveById=941320,    ctl:ruleRemoveById=941330,    ctl:ruleRemoveById=941340"
