SecRule REQUEST_URI "@beginsWith /admin/backup/upload" \
    "id:1000,\
    phase:1,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"

SecRule REQUEST_URI "@beginsWith /admin/backup/upload" \
    "id:1001,\
    phase:2,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"

SecRule REQUEST_URI "@beginsWith /admin/log-viewer" \
    "id:1002,\
    phase:1,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"

SecRule REQUEST_URI "@beginsWith /admin/log-viewer" \
    "id:1003,\
    phase:2,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"

SecRule REQUEST_URI "@beginsWith /admin/log-viewer" \
    "id:1004,\
    phase:3,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"

SecRule REQUEST_URI "@beginsWith /admin/log-viewer" \
    "id:1005,\
    phase:4,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"
